# ---- Build Stage ----
FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package*.json bun.lockb* bun.lock* ./
RUN bun install

COPY . .
RUN rm -f .env .env.local && cp .env.production .env

ENV NODE_ENV=production
RUN bun run build

# ---- Runner Stage ----
FROM oven/bun:1-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/.env ./.env

EXPOSE 3000

CMD ["bun", "run", "start"]