version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
    ports:
      - "3031:3031"
    environment:
      - NODE_ENV=development

volumes:
  mongo-data: