version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./server
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27018/chatDB

  mongo:
    image: mongo:latest
    command: mongod --port 27018
    ports:
        - '27018:27018'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: